<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluxor.Blazor.Web" Version="6.2.1.5" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" Version="6.2.1.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.3" />
    <PackageReference Include="Syncfusion.Blazor.Maps" Version="28.1.37" />
  </ItemGroup>

</Project>
